export class Countries{

    allCountries = [
        "Afghanistan",
        "Angola",
        "Albania",
        "United Arab Emirates",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Burundi",
        "Belgium",
        "Benin",
        "Burkina Faso",
        "Bangladesh",
        "Bulgaria",
        "Bosnia and Herz.",
        "Belarus",
        "Belize",
        "Bolivia",
        "Brazil",
        "Brunei",
        "Bhutan",
        "Botswana",
        "Central African Rep.",
        "Canada",
        "Switzerland",
        "Chile",
        "China",
        "Côte d'Ivoire",
        "Cameroon",
        "Dem. Rep. Congo",
        "Congo",
        "Colombia",
        "Costa Rica",
        "Cuba",
        "Czech Rep.",
        "Germany",
        "Djibouti",
        "Denmark",
        "Dominican Rep.",
        "Algeria",
        "Ecuador",
        "Egypt",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Finland",
        "Fiji",
        "Gabon",
        "United Kingdom",
        "Georgia",
        "Ghana",
        "Guinea",
        "Gambia",
        "Guinea-Bissau",
        "Eq. Guinea",
        "Greece",
        "Greenland",
        "Guatemala",
        "Guyana",
        "Honduras",
        "Croatia",
        "Haiti",
        "Hungary",
        "Indonesia",
        "India",
        "Ireland",
        "Iran",
        "Iraq",
        "Iceland",
        "Israel",
        "Italy",
        "Jamaica",
        "Jordan",
        "Japan",
        "Kazakhstan",
        "Kenya",
        "Kyrgyzstan",
        "Cambodia",
        "Korea",
        "Kuwait",
        "Lao PDR",
        "Lebanon",
        "Liberia",
        "Libya",
        "Sri Lanka",
        "Lesotho",
        "Lithuania",
        "Luxembourg",
        "Latvia",
        "Morocco",
        "Moldova",
        "Madagascar",
        "Mexico",
        "Macedonia",
        "Mali",
        "Myanmar",
        "Montenegro",
        "Mongolia",
        "Mozambique",
        "Mauritania",
        "Malawi",
        "Malaysia",
        "Namibia",
        "Niger",
        "Nigeria",
        "Nicaragua",
        "Netherlands",
        "Norway",
        "Nepal",
        "New Zealand",
        "Oman",
        "Pakistan",
        "Panama",
        "Peru",
        "Philippines",
        "Papua New Guinea",
        "Poland",
        "Dem. Rep. Korea",
        "Portugal",
        "Paraguay",
        "Palestine",
        "Qatar",
        "Romania",
        "Russia",
        "Rwanda",
        "W. Sahara",
        "Saudi Arabia",
        "Sudan",
        "S. Sudan",
        "Senegal",
        "Sierra Leone",
        "El Salvador",
        "Serbia",
        "Suriname",
        "Slovakia",
        "Slovenia",
        "Sweden",
        "Swaziland",
        "Syria",
        "Chad",
        "Togo",
        "Thailand",
        "Tajikistan",
        "Turkmenistan",
        "Timor-Leste",
        "Tunisia",
        "Turkey",
        "Taiwan",
        "Tanzania",
        "Uganda",
        "Ukraine",
        "Uruguay",
        "United States",
        "Uzbekistan",
        "Venezuela",
        "Vietnam",
        "Vanuatu",
        "Yemen",
        "South Africa",
        "Zambia",
        "Zimbabwe",
        "Somalia",
        "French Guiana",
        "France",
        "Spain",
        "Aruba",
        "Anguilla",
        "Andorra",
        "Antigua and Barb.",
        "Bahamas",
        "Bermuda",
        "Barbados",
        "Comoros",
        "Cape Verde",
        "Cayman Is.",
        "Dominica",
        "Falkland Is.",
        "Faeroe Is.",
        "Grenada",
        "Hong Kong",
        "St. Kitts and Nevis",
        "Saint Lucia",
        "Liechtenstein",
        "Maldives",
        "Malta",
        "Montserrat",
        "Mauritius",
        "New Caledonia",
        "Nauru",
        "Pitcairn Is.",
        "Puerto Rico",
        "Fr. Polynesia",
        "Singapore",
        "Solomon Is.",
        "São Tomé and Principe",
        "Sint Maarten",
        "Seychelles",
        "Turks and Caicos Is.",
        "Tonga",
        "Trinidad and Tobago",
        "St. Vin. and Gren.",
        "British Virgin Is.",
        "U.S. Virgin Is.",
        "Cyprus",
        "Reunion",
        "Mayotte",
        "Martinique",
        "Guadeloupe",
        "Curaco",
        "Canary Islands"
    ]

}